language: python
cache: pip

matrix:
  include:
    - env: TOXENV=flake8
      python: 3.6
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py36
      python: 3.6

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
