language: python
cache: pip

matrix:
  include:
    - env: TOXENV=flake8
      python: 3.5
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py35
      python: 3.5

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
